global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "weekly-glimpse"
    static_configs:
      - targets: ["host.docker.internal:9464"] # OpenTelemetry metrics endpoint

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"] # Node exporter metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alert manager configuration can be added here later
